### ISSUE TITLE
Lecture 4 link is broken

### ISSUE THREAD

**Issue by OriolLopezMassaguer** [haskell-beginners-2022/course-plan#4]
The link to the 4th lecture slides is broken:

https://slides.com/haskellbeginners2022/lecture-4

**Comment by chshersh** [comment]
@OriolLopezMassaguer What's broken with the link? 🤔 
I see that it correctly points to the fourth lecture.

**Comment by OriolLopezMassaguer** [comment]
When I access:

https://slides.com/haskellbeginners2022/lecture-4

It fails:

[image: image.png]

The other lecture links.

https://slides.com/haskellbeginners2022/lecture-3
<https://slides.com/haskellbeginners2022/lecture-3>

etc

worked correctly.

Oriol.

**Comment by chshersh** [comment]
@OriolLopezMassaguer That's strange 🤔 All links work for me.

I'm afraid, I can't help with resolving this issue as I can't observe the incorrect behaviour 😞

**Comment by OriolLopezMassaguer** [comment]
It's extrange... I will try with another browser/OS. Thanks

**Comment by OriolLopezMassaguer** [comment]
Hello;

I have contacted slides.com  and they say:

"The fourth presentation can't be opened because it only contains one slide. We prevent single-slide presentations shared by free accounts from being publicly accessed in order to prevent spam."

Regards.

**Comment by chshersh** [comment]
@OriolLopezMassaguer Thanks for getting to the root of this issue! 🔝 💯

**Comment by OriolLopezMassaguer** [comment]
You are wellcome.

So the next question is, will it be completed in the future?

**Comment by chshersh** [comment]
@OriolLopezMassaguer Of course it will be completed 🙂 
The course includes four lectures total.

**Comment by OriolLopezMassaguer** [comment]
Thanks!

Oriol.
