### ISSUE TITLE
Learn Haskell by participating in Hacktoberfest 2022!

### ISSUE THREAD

**Issue by chshersh** [haskell-beginners-2022/course-plan#8]
[Hacktoberfest](https://hacktoberfest.com/) is an annual event to encourage more people to participate in OSS. Usually, people contribute by improving other projects.

**✨ You can contribute by learning Haskell and developing new skills! ✨**

Below are the steps for participation:

1. 🔓 [Register on Hacktoberfest](https://hacktoberfest.com/).
2. ⭐️ Star [`course-plan`](https://hacktoberfest.com/) and [`exercises`](https://github.com/haskell-beginners-2022/exercises) repositories.
3. 🍴 Fork the [`exercises`](https://github.com/haskell-beginners-2022/exercises) repository.
4. 🍁 Add the `hacktoberfest` topic to your fork.
5. ℹ️ [Read information about the course](https://github.com/haskell-beginners-2022/course-plan#course-plan).
    * And you can also start learning Haskell by [watching Lecture 1](https://www.youtube.com/watch?v=6MsQcUprO9o&list=PLOJjn67NeYg9cWA4hyIWcxfaeX64pwo1c&ab_channel=chshersh)!
 6. 📜 [Read instructions for solving exercises](https://github.com/haskell-beginners-2022/exercises#exercises).
 7. 🧩 You can start by solving exercises to Lecture 1 and opening your first Pull Request to **your fork**!

That's all! You need to open **four** Pull Requests total to complete Hacktoberfest. Fortunately, the course contains exactly four lectures with the corresponding exercises so you can complete Hacktoberfest just by learning Haskell! 🎉

**Comment by Surya-Sastry** [comment]
Hey @chshersh, 
I have gone through your slides and the intro of your lectures. The slides were informative, and I felt the lectures were also crisp and clear. I am highly interested to work on this as a part of Hacktober fest. Could you please assign this issue to me?

**Comment by chshersh** [comment]
Hay @Surya-Sastry 👋🏻 

I'm glad you enjoyed the course content! 🤗 

There's no need to assign anyone to the issue. The course can be passed by multiple people who wants to learn Haskell 🙂 
You fork the `exercises` repository and mention me in the PR description (my mention is already automatically filled by the PR template), and I'll get a notification to review your solutions 🔔

**Comment by AbbeyIT** [comment]
Is this hacktoberfest accepted?

**Comment by chshersh** [comment]
@AbbeyIT Yes! 🙌🏻 

The only thing you need to do to satisfy the Hacktoberfest rules is to add the `hacktoberfest` topic to your fork. And then, any PRs to your fork are considere acceptable 🙂

**Comment by chshersh** [comment]
Hacktoberfest 2022 is over long time ago, so I'm closing this issue.
